### ISSUE TITLE
Unable to get receipt on tx confirmation

### ISSUE THREAD

**Issue by mikeshukshin** [MetaMask/web3-provider-engine#274] opened 2018-08-23 14:27 UTC
I created web3-provider via provider-engine using this code:
```javascript
import ProviderEngine from 'web3-provider-engine';
const FixtureSubprovider = require('web3-provider-engine/subproviders/fixture.js');
const NonceSubprovider = require('web3-provider-engine/subproviders/nonce-tracker.js');
const HookedWalletSubprovider = require('web3-provider-engine/subproviders/hooked-wallet.js');
const RpcSubprovider = require('web3-provider-engine/subproviders/rpc.js');
const WebsocketSubprovider = require('web3-provider-engine/subproviders/websocket');
const SubscriptionsSubprovider = require('web3-provider-engine/subproviders/subscriptions');

const engine = new ProviderEngine();

  // static results
  engine.addProvider(
    new FixtureSubprovider({
      web3_clientVersion: 'Web3Provider/v0.0.1',
      net_listening: true,
      eth_hashrate: '0x00',
      eth_mining: false,
      eth_syncing: true
    })
  );

  // pending nonce
  engine.addProvider(new NonceSubprovider());

  engine.addProvider(
    new HookedWalletSubprovider({
      getAccounts: function(cb) {
        ...
      },
      approveTransaction: function(txdata, cb) {
        ...
      },
      signTransaction: function(txdata, cb) {
        ...
      }
    })
  );

  // Subscription
  const subscriptionSubprovider = new SubscriptionsSubprovider();
  subscriptionSubprovider.on('data', (err, notification) => {
    engine.emit('data', err, notification);
  });
  engine.addProvider(subscriptionSubprovider);

  engine.addProvider(
    new WebsocketSubprovider({
      rpcUrl: INFURA_WS_URL
    })
  );

  engine.start();

  return engine;
```

It works fine. I send Tx and have got TxHash on callback. But I want to get behavior like MetaMask and get the receipt. How to do it?

```javascript
localWeb3.eth.sendTransaction({
      from: userAccount, 
      to: , 
      value: web3.toWei(1, "ether")
}, (error, txHash) => {
    // I have txHash
})
.on("receipt", function(receipt) {
      console.log('get receipt', receipt);
})```

**Comment by milonite** [comment] 2018-11-28 16:14
I have the same problem:

 ```
 contract.methods.someMethod(arg1, arg2).send(settings).on('transactionHash', function(hash){
        console.log(hash)
      }).on('confirmation', function(confirmationNumber, receipt){
        console.log(confirmationNumber)
      }).on('receipt', function(receipt){
          console.log(receipt);
      }).on('error', console.error); 
```

Gives me only the tx hash, not the repcipt nor an error

**Comment by kumavis** [comment] 2019-03-18 11:58
@mikeshukshin if you're using the websocket provider, you shouldnt need the subscription provider

im not sure of the cause of your issues, let me know if you find something

**Comment by mcmire** [comment] 2023-01-04 22:59
Sorry you were having trouble. Just an FYI: we don't recommend using this package any more as we actively phasing it out in favor of `json-rpc-engine` and its related packages. I'm going to close this in the meantime.

**Closed by mcmire** 2023-01-04 22:59 UTC
